actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'
jobs:
- job: copr_build
  targets:
    - centos-stream-9-x86_64
  trigger: pull_request
  branch: rhel9-branch
srpm_build_deps:
 - make
 - systemd
 - gettext
 - python3-devel
 - python3-setuptools

downstream_package_name: python-blivet
