actions:
  post-upstream-clone:
    # we need to set email and username for the merge commit
    - 'git config user.email "blivet-ci@example.com"'
    - 'git config user.name "Blivet CI"'
    # merge the release branch to get correct version in spec
    - 'git merge --ff origin/3.10-release'
    # bump release to 99 to always be ahead of Fedora builds
    - 'bash -c "sed -i -r \"s/Release:(\s*)\S+/Release: 99%{?dist}/\" python-blivet.spec"'
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'
  fix-spec-file:
    # define the Source variables
    - bash -c "sed -i python-blivet.spec -e \"s/http.*%{realname}-%{realversion}.tar.gz/blivet-${PACKIT_PROJECT_VERSION}.tar.gz/\""
    - bash -c "sed -i python-blivet.spec -e \"s/http.*%{realname}-%{realversion}-tests.tar.gz/blivet-${PACKIT_PROJECT_VERSION}-tests.tar.gz/\""
    # fill in Release as if packit would have done it
    - bash -c "sed -i python-blivet.spec -e \"s/Release:.*/Release:\ ${PACKIT_RPMSPEC_RELEASE}%{?dist}/\""

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all
  trigger: pull_request

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: blivet-daily
  branch: 3.10-devel
  preserve_project: true

- job: tests
  trigger: pull_request
  targets:
  - fedora-latest-stable
  tf_extra_params:
    environments:
      - artifacts:
        - type: repository-file
          id: https://copr.fedorainfracloud.org/coprs/g/storage/blivet-daily/repo/fedora-$releasever/group_storage-blivet-daily-fedora-$releasever.repo

# run tests for udisks consumers, see plans/ with `revdeps == yes`
- job: tests
  identifier: revdeps
  trigger: pull_request
  notifications:
    failure_comment:
      message: "Blivet-GUI tests failed for commit {commit_sha}. @vojtechtrefny please check."
  targets:
    - fedora-latest-stable
  tf_extra_params:
    environments:
      - artifacts:
        - type: repository-file
          id: https://copr.fedorainfracloud.org/coprs/g/storage/blivet-daily/repo/fedora-$releasever/group_storage-blivet-daily-fedora-$releasever.repo
        tmt:
          context:
            revdeps: "yes"

srpm_build_deps:
 - git
 - make
 - systemd
 - gettext
 - python3-devel
 - python3-setuptools

downstream_package_name: python-blivet
