#!/usr/bin/python3
import dbus
import dbus.mainloop.glib
from gi.repository import GLib

from blivet.dbus import DBusBlivet

dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
system_bus = dbus.SystemBus()

mainloop = GLib.MainLoop()
blivet_obj = DBusBlivet()
mainloop.run()
